### ISSUE TITLE
Make hostname and port for WebUI container dynamically configurable

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-docker#13]
today the hostname is hard encoded in config.js and then copied into the image
problem is if the config.js is wrong you do not only need to remove the container but also the image and rebuild everything

exepectation:
I want to be able to just stop the webui container and start with another host name and port

**Comment by metasnw** [comment]
I did lose an hour troubleshooting strange webUI to find out there was a typo in config.js that I had to do for the weekly update.

**Comment by metas-ts** [comment]
Hi @metas-jb @metasnw 
FYI: in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1013 i implemented setting the config.js on runtime.
You might want to take a look at https://github.com/metasfresh/metasfresh-webui-frontend/tree/master/docker . Note that the `Dockerfile-dev` also contains some documentation.

**Comment by metas-jb** [comment]
Tested and implemented.

You are now able to set the URL of your server in the `docker-compose.yml`.
Just uncomment the following lines and replace the URL with your externally accessible hostname or IP address
```
  #environment:
    #- WEBAPI_URL=http://example.com:8080
```

Example:
You're currently already running metasfresh-docker and want to change the publicly accessible URL for metasfresh to `http://myserver.com`

* login to your dockerhost where metasfresh-docker is running
* got to the base directory of metasfresh-docker (eg. /opt/metasfresh-docker/ )
* modify `./docker-compose.yml`: uncomment the above lines and modify the URL so it looks like this:
```
  environment:
    - WEBAPI_URL=http://myserver.com
```
(Note: beware of indentation on yml-files)
* update your metasfresh-docker project: `docker-compose up -d`
* the container `metasfreshdocker_webui_1` will be recreated
* Done! metasfresh should now be accessible via browser using `http://myserver.com`
