### ISSUE TITLE
Map each JVM port to outside (configurable)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-docker#20]
Please map each JVM's debugging port to outside.
i.e.
* metasfresh-server, port=8788
* metasfresh-webui-api, port=8789

The debugging ports shall not be mapped by default but only if configured.
We will enable them only on IT servers.

**Comment by metas-jb** [comment]
You are able to start a "debug" stack by copying `./extras/docker-compose_debug.yml` to the main directory and start it by using `docker-compose -f docker-compose_debug.yml`
