### ISSUE TITLE
Why is a container named Reverent Thompson?

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-docker#22]
![image](https://cloud.githubusercontent.com/assets/16079655/26577745/b18053e2-452d-11e7-8453-699cb89c8e26.png)

**Comment by metas-jb** [comment]
This can happen if you do not use `docker-compose` to create the image OR if you did not remove the image `mf_db_1` prior to building a new image.

To avoid duplicates and for easier access, docker automatically assigns names to containers.
With docker-compose, they are defined in the docker-compose file.

**Comment by teosarca** [comment]
but i like the name  :)))
btw, elasticsearch has the same approach if you are not setting a node name... but there is more Darth Vader-ish.

**Comment by metasnw** [comment]
thx for the explainations
