### ISSUE TITLE
do not save any settings to docker image filesystem

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-docker#25]
to avoid problems like #24 

expectation:
all settings are given to the container via variables and the config files use those

e.g. you can start the app container with the ports you want to use and do not have to recreate the image

https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container

https://stackoverflow.com/questions/23735149/docker-image-vs-container

**Comment by metas-jb** [comment]
I think this is solvable by using `expose:` not by `Dockerfile` but by `docker-compose.yml`

See: https://docs.docker.com/compose/compose-file/compose-file-v1/#expose
for additional info

**Comment by metasnw** [comment]
I guess the question is more how can we have docker containers without images.
in case of db that is impossible (I guess?) but for the others it should be doable

**Comment by metasnw** [comment]
> I think this is solvable by using expose: not by Dockerfile but by docker-compose.yml

very nice. so we could release a new docker-compose.yml file

**Comment by teosarca** [comment]
(just my 2 cents.... it would be nice if the images would be completely immutable)

**Comment by metas-jb** [comment]
>I guess the question is more how can we have docker containers without images.

Can be done already.
You can use the `docker-src` directory as main folder for building your local container-images.
Keep in mind, this would make dockerhub completely superfluous.

**Comment by metas-jb** [comment]
>in case of db that is impossible (I guess?) but for the others it should be doable

Not this is not impossible.
As with all services, the required/weekly updated jar/tar.gz/pgdump files just need to be publicly downloadable and stored over a longer period of time (eg. a filehost).

**Comment by metas-jb** [comment]
>(just my 2 cents.... it would be nice if the images would be completely immutable)

I think this references to #13 since you can pass all config-variables in our application via environment variables to the containers which then just needs to use the environment-variables in their configs.

**Comment by metasnw** [comment]
addressed by #13
