### ISSUE TITLE
add msv3server to metasfresh-docker as "extras"

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-docker#34]
Create a docker image for https://github.com/metasfresh/metasfresh/tree/master/de.metas.vertical.pharma.msv3.server

**Comment by teosarca** [comment]
For msv3 server configuration, see https://github.com/metasfresh/metasfresh/issues/3716

**Comment by metas-ts** [comment]
The docker image contains the msv3-server, but not postgresql or RabbitMQ

It can be run with the following environment variables

 * `DB_HOST` (default: localhost)
 * `DB_PORT` (default: 5432)
 * `DB_NAME` (default: msv3server)
 * `DB_USER` (default: msv3server)
 * `DB_PASSWORD` (default: msv3server)
 * `DB_WAIT_FOR_DBMS` (default: y)

 * `RABBITMQ_HOST` (default: localhost)
 * `RABBITMQ_PORT` (default: 5672)
 * `RABBITMQ_USER` (default: guest)
 * `RABBITMQ_PASSWORD` (default: value taken from `$secret_rabbitmq_password`)

 * `DEBUG_PORT` (default: 8791)
 * `DEBUG_SUSPEND` (default n)
 * `DEBUG_PRINT_BASH_CMDS` (default: n)
 * `DEBUG_JPA_SHOW_SQL` (default: false)
 * `METASFRESH_ADMIN_URL` (default: NONE)
 * `JAVA_MAX_HEAP` (default: 128M)
 * `SERVER_PORT` (default: 8080)
 * `SERVER_REQUEST_ALL_DATA_ON_STARTUP` (default: true)
